# @file drag_race.yaml
# @author Sirui Song
# @author Jungwook Lee
# @author Toni Ogunmade(oluwatoni)
# @competition IARRC 2018

#Map Size
TrajRoll/MAP_WIDTH:            1100 # in cm
TrajRoll/MAP_HEIGHT:           700  # in cm
TrajRoll/RESOLUTION:           0.01 # in m

#Trajectory Generation Parameters
TrajRoll/NUM_PATHS:            51
TrajRoll/TRAJECTORY_STEPS:     70
TrajRoll/MIN_STOPPING_DIST:    0.2
TrajRoll/STOPPING_FACTOR:      0.15

#Desired Velocity Setup
TrajRoll/STRAIGHT_SPEED:       2.0

#Vehicle Parameters
TrajRoll/MAX_STEERING_ANGLE:   0.5
TrajRoll/CAR_WIDTH:            0.2
TrajRoll/DIST_REWARD_FACTOR:   4.0
TrajRoll/MIN_OFFSET_DIST:      0.05

#For Debugging 
#Visualization
TrajRoll/VISUALIZATION:        true
TrajRoll/DEBUG_ON:             false
