# @file drag_race.yaml
# @author Sirui Song
# @author Jungwook Lee
# @author Toni Ogunmade(oluwatoni)
# @competition IARRC 2018

#Map Size
TrajRoll/MAP_WIDTH:            1100
TrajRoll/MAP_HEIGHT:           700
TrajRoll/RESOLUTION:           0.01

#Trajectory Generation Parameters
TrajRoll/PLANNER_VELOCITY:     1.0
TrajRoll/NUM_PATHS:            101
TrajRoll/TRAJECTORY_STEPS:     100
TrajRoll/dt:                   0.025
TrajRoll/OBS_THRESHOLD:        0
TrajRoll/MIN_STOPPING_DIST:    0.2
TrajRoll/STOPPING_FACTOR:      0.15

#Desired Velocity Setup
TrajRoll/STRAIGHT_SPEED:       0.5

#Vehicle Parameters
TrajRoll/MAX_STEERING_ANGLE:   0.7
TrajRoll/CAR_WIDTH:            0.2
TrajRoll/DIST_COST_FACTOR:     10.0
TrajRoll/MIN_OFFSET_DIST:      0.05

#For Debugging 
#Visualization
TrajRoll/VISUALIZATION:        true
TrajRoll/DEBUG_ON:             false
